name: CI

on:
  push:
    branches: [ main ]
    tags: [ v* ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Build & Push Docker Images
      env:
        DOCKERHUB_OWNER: ${{ secrets.DOCKERHUB_USERNAME }}
      run: make

